### ISSUE TITLE
How about an EDMC plugin?

### ISSUE THREAD

**Issue by inorton** [vovchisko/ed-void-client#4]
I think I could write you one?

**Comment by vovchisko** [comment]
@inorton VOID collect market data now. But there is no UI part to display it yet. And this client not support plugins. Actually it only sends journals/data to ed-void server.

**Comment by inorton** [comment]
I mean, collect the journal, status and cmdr data using edmc instead

**Comment by vovchisko** [comment]
@inorton Plugin for EDMC reporting data to ED-VOID? Naah... I started ed-void because I wanted to not run anything heavy, like EDD/EDMC on low-end PC and specially when you have 1 monitor.

Also API & Socket protocols changes frequently (and  as expected there is no documentation).
As for me it's hard to image 3~3rd party plugin maintain this way.

Sure you can try, but server may updates like ... suddenly. Few times per week.
